name: bubble_tea_shop_flutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  diamond_fab: "^0.1.0"
  flutter_swiper: ^1.0.4
  splashscreen: ^1.1.0
  flutter_statusbarcolor: ^0.0.3
  flutter_webview_plugin: ^0.2.1+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.6.0



flutter_icons:
  android: true 
  ios: "Example-Icon"
  image_path: "images/icon.png"
  adaptive_icon_background: "#FFA500"

  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/assamtea.png
   - images/bubbletea.png
   - images/icetea.png
   - images/jasminetea.png
   - images/lemontea.png
   - images/milktea.png
   - images/tarotea.png
   - images/blacktea.png
   - images/chocolatetea.png
   - images/ppl1.jpg
   - images/ppl2.jpg
   - images/ppl3.jpg
   - images/welcome.jpg
   - images/about.jpg
   - images/icon.png
   - images/workingplace.jpg
   - images/food1.jpg
   - images/food2.jpg
   - images/food3.jpg
   - images/food4.jpg
   - images/food5.jpg
   - images/food6.jpg
   - images/food7.jpg

   



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts: 
  - family: Stocky
    fonts:
        - asset: fonts/stocky.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
